[book]
authors = ["Chaitanya Joshi"]
language = "en"
multilingual = false
src = "src"
title = "Morpho Manual"
[output.html]
mathjax-support = true
git-repository-url = "https://github.com/joshichaitanya3/morpho-manual"


[output.html.fold]
enable = true    # whether or not to enable section folding
level = 0         # the depth to start folding

[build]
create-missing = true # This is kept for convenience, but CI sets it to false
use-default-preprocessors = false
extra-watch-dirs = ["po"]

[preprocessor.links]

[preprocessor.gettext]
command = "cargo run -p i18n-helpers --bin mdbook-gettext --locked --release --"
before = ["links"]
