[book]
authors = ["Chaitanya Joshi"]
language = "en"
multilingual = false
src = "src"
title = "Morpho Manual"
[output.html]
mathjax-support = true
git-repository-url = "https://github.com/joshichaitanya3/morpho-manual"
