[book]
authors = ["Chaitanya Joshi"]
language = "en"
multilingual = false
src = "src"
title = "Morpho Manual"
[output.html]
mathjax-support = true
additional-css = ["theme/css/language-picker.css"]
git-repository-url = "https://github.com/joshichaitanya3/morpho-manual"

[preprocessor.gettext]
